name: Publish
on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read  # Allows the workflow to read the repository contents
  packages: write # Allows the workflow to publish packages

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@angryart'
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}


